package org.zyq.tomcat.view.table_list;

import org.apache.commons.io.FileUtils;
import org.zyq.core.lang.Str;
import org.zyq.swing.SwingUtils;
import org.zyq.swing.TableUtils;
import org.zyq.tomcat.CONFIG;
import org.zyq.tomcat.view.tabel_add.Tomcat_add;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.ObjectOutputStream;

public class Tomcat_list {

    private JPanel list;
    private JButton addButton;
    private JButton selectButton;
    private JButton daoruButton;
    private JButton saveButton;
    private JLabel peizhiLabel;
    private JLabel workLabel;
    private JTable listTable;
    private JScrollPane sp1;

    public Tomcat_list() {
        $$$setupUI$$$();
        saveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    ObjectOutputStream oos = new ObjectOutputStream(FileUtils.openOutputStream(new File(CONFIG.defaultConfig)));
                    oos.writeObject(CONFIG.subject);
                    oos.close();
                } catch (Exception e1) {
                    e1.printStackTrace();
                }
            }
        });
        addButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (Str.isBlank(CONFIG.subject.getWorkspace())) {
                    JOptionPane.showMessageDialog($$$getRootComponent$$$(), "请先选择工作目录", "错误", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                SwingUtils.setContent(new Tomcat_add().$$$getRootComponent$$$());
            }
        });

        selectButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String s = "D:/";
                if (CONFIG.subject.getWorkspace() != null && !CONFIG.subject.getWorkspace().isEmpty())
                    s = CONFIG.subject.getWorkspace();
                JFileChooser jFileChooser = new JFileChooser(s);
                jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                jFileChooser.showDialog(new JLabel(), "请选择工作目录");
                File dir = jFileChooser.getSelectedFile();
                if (dir != null) CONFIG.subject.setWorkspace(dir.getAbsolutePath());
                SwingUtils.setContent(new Tomcat_list().$$$getRootComponent$$$());
            }
        });
        workLabel.setText(CONFIG.subject.getWorkspace() == null ? "无" : CONFIG.subject.getWorkspace());
        workLabel.setToolTipText(workLabel.getText());
        workLabel.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                if (e.getClickCount() == 2 && Str.notBlank(CONFIG.subject.getWorkspace())) {
                    Str.setSysClipboardText(CONFIG.subject.getWorkspace());
                    JOptionPane.showMessageDialog($$$getRootComponent$$$(), "复制成功", "提示", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });
    }

    private void createUIComponents() {
        listTable = new ZTable();
        listTable.setModel(new Table_model());
        TableUtils.hideColumn(listTable, 0);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        list = new JPanel();
        list.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setText("tomcat管理工具");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.BOTH;
        list.add(label1, gbc);
        selectButton = new JButton();
        selectButton.setHorizontalAlignment(2);
        selectButton.setText("选择工作目录");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        list.add(selectButton, gbc);
        saveButton = new JButton();
        saveButton.setText("保存配置");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        list.add(saveButton, gbc);
        daoruButton = new JButton();
        daoruButton.setText("导入配置文件");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        list.add(daoruButton, gbc);
        addButton = new JButton();
        addButton.setText("新增");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        list.add(addButton, gbc);
        workLabel = new JLabel();
        workLabel.setEnabled(true);
        workLabel.setPreferredSize(new Dimension(100, 20));
        workLabel.setText("无");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 0, 30);
        list.add(workLabel, gbc);
        peizhiLabel = new JLabel();
        peizhiLabel.setPreferredSize(new Dimension(100, 20));
        peizhiLabel.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        list.add(peizhiLabel, gbc);
        sp1 = new JScrollPane();
        sp1.setPreferredSize(new Dimension(400, 420));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        list.add(sp1, gbc);
        sp1.setViewportView(listTable);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipady = 100;
        list.add(spacer1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return list;
    }
}
