package org.zyq.tomcat.view.tomcat_option;

import org.zyq.swing.SwingUtils;
import org.zyq.tomcat.view.table_list.Tomcat_list;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Tomcat_option {
    private JPanel o;
    private JButton backButton;
    private JButton qidongButton;
    private JButton tingzhiButton;
    private JButton deButton;
    private JButton sureButton;

    public Tomcat_option(String id) {
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SwingUtils.setContent(new Tomcat_list().$$$getRootComponent$$$());
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        o = new JPanel();
        o.setLayout(new GridBagLayout());
        backButton = new JButton();
        backButton.setText("返回");
        backButton.setToolTipText("返回");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        o.add(backButton, gbc);
        qidongButton = new JButton();
        qidongButton.setText("启动");
        qidongButton.setToolTipText("启动");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        o.add(qidongButton, gbc);
        tingzhiButton = new JButton();
        tingzhiButton.setText("停止");
        tingzhiButton.setToolTipText("停止");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        o.add(tingzhiButton, gbc);
        deButton = new JButton();
        deButton.setText("部署");
        deButton.setToolTipText("部署");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        o.add(deButton, gbc);
        sureButton = new JButton();
        sureButton.setText("确定");
        sureButton.setToolTipText("确定");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        o.add(sureButton, gbc);
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(4);
        label1.setText("当前TOMCAT为：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        o.add(label1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return o;
    }
}
