package org.zyq.tomcat.view.tomcat_option;

import org.zyq.swing.SwingUtils;
import org.zyq.tomcat.CONFIG;
import org.zyq.tomcat.view.table_list.Tomcat_list;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;

public class Tomcat_option {
    private JPanel o;
    private JButton backButton;
    private JButton qidongButton;
    private JButton tingzhiButton;
    private JButton deButton;
    private JButton sureButton;
    private JButton deleteButton;
    private JLabel nowtomcat;

    public Tomcat_option(final String id) {
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SwingUtils.setContent(new Tomcat_list().$$$getRootComponent$$$());
            }
        });
        deleteButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int index = -1;
                for (int i = 0; i < CONFIG.subject.getList().size(); i++) {
                    if (CONFIG.subject.getList().get(i).getId().equals(id)) index = i;
                }
                if (index != -1) CONFIG.subject.getList().remove(index);
                JOptionPane.showMessageDialog($$$getRootComponent$$$(), "删除成功", "提示", JOptionPane.INFORMATION_MESSAGE);
                SwingUtils.setContent(new Tomcat_list().$$$getRootComponent$$$());
            }
        });
        final String s = CONFIG.subject.getWorkspace() + "\\" + id;
        nowtomcat.setText(s);
        nowtomcat.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                if (e.getClickCount() == 2) {
                    try {
                        Runtime.getRuntime().exec("explorer " + s);
                    } catch (IOException e1) {
                        e1.printStackTrace();
                    }
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        o = new JPanel();
        o.setLayout(new GridBagLayout());
        backButton = new JButton();
        backButton.setText("返回");
        backButton.setToolTipText("返回");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        o.add(backButton, gbc);
        qidongButton = new JButton();
        qidongButton.setText("启动");
        qidongButton.setToolTipText("启动");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        o.add(qidongButton, gbc);
        tingzhiButton = new JButton();
        tingzhiButton.setText("停止");
        tingzhiButton.setToolTipText("停止");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        o.add(tingzhiButton, gbc);
        deButton = new JButton();
        deButton.setText("部署");
        deButton.setToolTipText("部署");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        o.add(deButton, gbc);
        sureButton = new JButton();
        sureButton.setText("确定");
        sureButton.setToolTipText("确定");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        o.add(sureButton, gbc);
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(4);
        label1.setText("当前TOMCAT为：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        o.add(label1, gbc);
        deleteButton = new JButton();
        deleteButton.setText("删除");
        deleteButton.setToolTipText("删除");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        o.add(deleteButton, gbc);
        nowtomcat = new JLabel();
        nowtomcat.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.VERTICAL;
        o.add(nowtomcat, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return o;
    }
}
